/**
 * Milestone 15 end-to-end checks R1 to R9 (TODO.md): HoloML hardening.
 * Limits (GitHub issue #23), keyboard, screen readers, and motion (#25),
 * and the inspector's Scene part (#28). The large files are generated by
 * the fixture server (holoml/gen/...), so the repository holds none.
 */
import { mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { startFixtureServer, type FixtureServer } from './fixture-server';
import {
  clickAt,
  clickUntil,
  focusedTab,
  inPage,
  launch,
  pressInPage,
  pressInShell,
  project,
  removeFolder,
  shellCall,
  sleep,
  waitFor,
  softwareRenderer,
  waitForPage,
  watchStalls,
  type Harness,
  type Point,
} from './harness';

let server: FixtureServer;
const profiles: string[] = [];

beforeAll(async () => {
  server = await startFixtureServer();
});

afterAll(async () => {
  await server?.close();
  for (const dir of profiles) await removeFolder(dir);
});

function newProfile(settings: object): string {
  const dir = mkdtempSync(join(tmpdir(), 'hypersol-e2e-profile-'));
  profiles.push(dir);
  writeFileSync(join(dir, 'settings.json'), JSON.stringify(settings));
  return dir;
}

type Vec = [number, number, number];
interface Model {
  src: string;
  state: string;
  animation: { name: string; playing: boolean; time: number } | null;
}
interface LeftOut {
  what: string;
  why: string;
}

/** The viewer's facts in a HoloML page (an address part picks the page). */
function holo<T>(h: Harness, expression: string, page: string): Promise<T> {
  return inPage<T>(h, `window.__holoml ? (${expression}) : undefined`, page);
}

async function sceneReady(h: Harness, page: string, timeoutMs = 20_000): Promise<void> {
  await waitFor('the scene ready', () => holo<boolean>(h, 'window.__holoml.ready', page), (r) => r === true, timeoutMs);
}

async function open(h: Harness, url: string, page: string, timeoutMs?: number): Promise<void> {
  await shellCall(h, 'showUrl', url);
  await waitForPage(h, page);
  await sceneReady(h, page, timeoutMs);
}

const models = (h: Harness, page: string) => holo<Model[]>(h, 'window.__holoml.models()', page);
const leftOut = (h: Harness, page: string) => holo<LeftOut[]>(h, 'window.__holoml.leftOut()', page);
const busy = (h: Harness, page: string) => holo<boolean>(h, 'window.__holoml.busy', page);
const noticeText = (h: Harness, page: string) =>
  inPage<string>(h, `(() => { const n = document.querySelector('[data-testid="holoml-notice"]'); return n && !n.hidden ? n.textContent : ''; })()`, page);
const marked = (h: Harness, id: string, page: string) => holo<boolean>(h, `window.__holoml.object(${JSON.stringify(id)}).marked`, page);
const stateOf = async (h: Harness, page: string, src: string) => (await models(h, page)).find((m) => m.src.includes(src))?.state;
/** The text of what has focus in the page's outline. */
const focused = (h: Harness, page: string) => inPage<string>(h, 'document.activeElement?.textContent ?? ""', page);

/** Runs a DevTools protocol command in the page (reduced motion, the accessibility tree, garbage collection). */
async function inDebugger<T>(h: Harness, page: string, method: string, params: object = {}): Promise<T> {
  return h.app.evaluate(
    async ({ webContents }, { page, method, params }) => {
      const guest = webContents.getAllWebContents().filter((w) => w.getType() === 'webview' && w.getURL().includes(page)).pop();
      if (!guest) throw new Error(`No page ${page}`);
      if (!guest.debugger.isAttached()) guest.debugger.attach('1.3');
      return guest.debugger.sendCommand(method, params);
    },
    { page, method, params },
  ) as Promise<T>;
}

async function detachDebugger(h: Harness, page: string): Promise<void> {
  await h.app.evaluate(
    ({ webContents }, page) => {
      for (const w of webContents.getAllWebContents()) if (w.getType() === 'webview' && w.getURL().includes(page) && w.debugger.isAttached()) w.debugger.detach();
    },
    page,
  );
}

describe('R1, R2: models over the limits are left out and marked; the rest shows', () => {
  let h: Harness;
  beforeAll(async () => {
    h = await launch(server.url('holoml/limits-files.holoml'));
  });
  afterAll(async () => h?.close());

  it('R1 a model file over 32 MB is left out with a mark and a notice', async () => {
    const PAGE = 'limits-files.holoml';
    await waitForPage(h, PAGE);
    await sceneReady(h, PAGE);
    await waitFor('the big model settled', () => stateOf(h, PAGE, 'mb=40'), (s) => s === 'left-out', 30_000);
    expect(await stateOf(h, PAGE, 'mb=1')).toBe('loaded');
    expect(await marked(h, 'huge', PAGE)).toBe(true);
    expect(await marked(h, 'small', PAGE)).toBe(false);
    expect(await holo<string[]>(h, 'window.__holoml.labels()', PAGE)).toContain('Still here');
    const out = await leftOut(h, PAGE);
    expect(out).toHaveLength(1);
    expect(out[0]!.why).toMatch(/larger than 32 MB/);
    const notice = await noticeText(h, PAGE);
    expect(notice).toContain('One thing on this page was left out');
    expect(notice).toMatch(/larger than 32 MB/);
    // Nothing past the file's limit was kept: at most 32 MB and a piece for it.
    expect(server.hits.get('/holoml/gen/zeros.bin?bytes=41943040')).toBe(1);
  });

  it('R1 models adding up to more than 128 MB: the one that crosses it is left out, the others show', async () => {
    const PAGE = 'limits-total.holoml';
    await open(h, server.url(`holoml/${PAGE}`), PAGE);
    await waitFor('all five settled', async () => (await models(h, PAGE)).map((m) => m.state), (s) => s.length === 5 && s.every((x) => x === 'loaded' || x === 'left-out'), 60_000);
    const states = (await models(h, PAGE)).map((m) => m.state);
    expect(states.filter((s) => s === 'left-out')).toHaveLength(1);
    expect(states.filter((s) => s === 'loaded')).toHaveLength(4);
    const out = await leftOut(h, PAGE);
    expect(out[0]!.why).toMatch(/128 MB in all/);
    const id = `m${states.indexOf('left-out') + 1}`;
    expect(await marked(h, id, PAGE)).toBe(true);
    expect(await noticeText(h, PAGE)).toMatch(/128 MB/);
  });

  it('R2 an 8192 by 8192 picture, and models past 2 million triangles in all, are left out the same way', async () => {
    const PAGE = 'limits-costs.holoml';
    await open(h, server.url(`holoml/${PAGE}`), PAGE);
    await waitFor('all four settled', async () => (await models(h, PAGE)).map((m) => m.state), (s) => s.length === 4 && s.every((x) => x === 'loaded' || x === 'left-out'), 30_000);
    expect(await stateOf(h, PAGE, 'box.gltf')).toBe('loaded'); // the first, plain model
    expect(await stateOf(h, PAGE, 'img=8192')).toBe('left-out');
    expect(await marked(h, 'picture', PAGE)).toBe(true);
    const tri = [await stateOf(h, PAGE, 'n=a'), await stateOf(h, PAGE, 'n=b')];
    expect(tri.sort()).toEqual(['left-out', 'loaded']);
    const whys = (await leftOut(h, PAGE)).map((o) => o.why);
    expect(whys.some((w) => /8192 by 8192 pixels is larger than 4096 by 4096/.test(w))).toBe(true);
    expect(whys.some((w) => /triangles would pass the page's 2,000,000/.test(w))).toBe(true);
    expect(await noticeText(h, PAGE)).toContain('2 things on this page were left out');
    // The picture was refused from its header: the model's buffer and the picture were fetched, nothing decoded.
    expect(server.hits.get('/holoml/gen/claim.png?w=8192&h=8192')).toBe(1);
  });
});

describe('R3: a page of 20,000 elements', () => {
  let h: Harness;
  /**
   * How long the shell took to answer while the page loaded and built, what
   * held it up, and how long one more answer took once all was shown: the
   * first check measures them, and the second holds them to the budget.
   */
  let answered: { times: number[]; why: string; last: number } | null = null;
  /**
   * Longest one answer of the shell may take before the first check gives
   * up: far past the 200 ms budget, and past the 2.7 s an answer has taken
   * drawn in software (GitHub's Linux machines). A question to the shell
   * has no limit of its own, so once, in software, the check waited its
   * whole 60 s on one answer and said only that its time was up; now it
   * says what it waited for, and how long the answer before it took.
   */
  const ANSWER_LIMIT_MS = 20_000;
  const STALL_REPORT_LIMIT_MS = 5000;
  beforeAll(async () => {
    h = await launch(server.url('link-a.html'));
  });
  afterAll(async () => h?.close());

  /** `p`'s value, or, when none has come within `limitMs`, an error with `message`'s words (asked for only then). */
  async function within<T>(p: Promise<T>, limitMs: number, message: () => Promise<string>): Promise<T> {
    let timer: ReturnType<typeof setTimeout> | undefined;
    const late = new Promise<'late'>((resolve) => {
      timer = setTimeout(() => resolve('late'), limitMs);
    });
    try {
      const result = await Promise.race([p.then((value) => ({ value })), late]);
      if (result === 'late') throw new Error(await message());
      return result.value;
    } finally {
      clearTimeout(timer);
    }
  }

  it('R3 shows the first part, says the rest was left out, and the browser goes on answering', async () => {
    const PAGE = 'many.holoml';
    await shellCall(h, 'showUrl', server.url('holoml/gen/many.holoml?n=20000'));
    // While the page loads and builds, the browser's own controls answer at once.
    const stalls = await watchStalls(h);
    const asked = Date.now();
    const times: number[] = [];
    /** The stall watch's report, if it can be had (a hung shell answers that neither). */
    const stallReport = () =>
      within(stalls(), STALL_REPORT_LIMIT_MS, async () => `the stall watch did not answer within ${STALL_REPORT_LIMIT_MS} ms`).catch((e: unknown) => String(e instanceof Error ? e.message : e));
    /** One answer of the shell (its tabs hook) and how long it took, or an error saying what was waited for. */
    const answer = async (when: string) => {
      const t = performance.now();
      await within(shellCall(h, 'tabs'), ANSWER_LIMIT_MS, async () => {
        const before = times.length === 0 ? 'no answer before it' : `${times.length} answers before it, the last took ${times[times.length - 1]!.toFixed(0)} ms`;
        return `The shell did not answer within ${ANSWER_LIMIT_MS} ms (asked for its tabs ${when}, ${Date.now() - asked} ms after the page was asked for; ${before}; ${await stallReport()})`;
      });
      return performance.now() - t;
    };
    const until = Date.now() + 3000;
    while (Date.now() < until) {
      times.push(await answer('while the page loaded and built'));
      await sleep(50);
    }
    const why = await stallReport();
    await waitForPage(h, PAGE);
    await sceneReady(h, PAGE);
    expect(await holo<string[]>(h, 'window.__holoml.labels()', PAGE)).toContain('First of many');
    const out = await leftOut(h, PAGE);
    expect(out).toHaveLength(1);
    expect(out[0]!.what).toMatch(/^[\d,]+ elements$/);
    expect(out[0]!.why).toBe("past the page's limit of 10,000");
    expect(await noticeText(h, PAGE)).toMatch(/elements: past the page's limit of 10,000/);
    const last = await answer('once the page was shown');
    // Every question was answered; how soon is the next check's.
    expect(times.length).toBeGreaterThan(0);
    answered = { times, why, last };
  });

  it('R3 the browser stays responsive: while the page loads and builds, and after, it answers within 200 ms (with a graphics card)', async (ctx) => {
    expect(answered, 'the check before this one measured the answers').not.toBeNull();
    const { times, why, last } = answered!;
    const answers = `shell answers took ${times.map((t) => t.toFixed(0)).join(', ')} ms; ${why}; a last answer took ${last.toFixed(0)} ms`;
    // Within 200 ms with a graphics card. Drawn in software (GitHub's machines), the browser's
    // page and the scene share one software GPU process, which the scene's first draw keeps
    // busy for seconds: there the times are measured and logged, and the check is skipped, not
    // passed, as the other budgets are (owner, prompt 96).
    const software = await softwareRenderer(h);
    if (software) {
      console.log(`R3: ${answers}; the 200 ms budget not checked: drawing in software (${software})`);
      ctx.skip(`the 200 ms budget is for graphics hardware; drawing in software (${software})`);
    }
    expect(Math.max(...times), answers).toBeLessThan(200);
    expect(last, answers).toBeLessThan(200);
  });
});

describe('R4, R6: stopping, and focus that holds', () => {
  let h: Harness;
  const PAGE = 'slow.holoml';
  const STOP = 'hs-toolbar [data-testid="stop"]';
  const RELOAD = 'hs-toolbar [data-testid="reload"]';
  beforeAll(async () => {
    h = await launch(server.url('link-a.html'));
  });
  afterAll(async () => h?.close());

  async function openSlow(): Promise<number> {
    const started = Date.now();
    // Not "ready": that waits for every model, and one never finishes.
    await shellCall(h, 'showUrl', server.url(`holoml/${PAGE}?t=${started}`));
    await waitForPage(h, `${PAGE}?t=${started}`);
    await waitFor('the small model loaded', () => stateOf(h, PAGE, 'box.gltf'), (s) => s === 'loaded');
    expect(await busy(h, PAGE)).toBe(true);
    return started;
  }

  it('R4 the stop button stops a model that never finishes, at once', async () => {
    await openSlow();
    await waitFor('the stop button', () => h.shell.locator(STOP).count(), (n) => n === 1);
    const t = Date.now();
    await h.shell.click(STOP);
    await waitFor('left out', () => stateOf(h, PAGE, 'never.gltf'), (s) => s === 'left-out', 2000);
    expect(Date.now() - t).toBeLessThan(2000);
    expect((await leftOut(h, PAGE))[0]!.why).toMatch(/stopped before it finished loading/);
    expect(await marked(h, 'slow', PAGE)).toBe(true);
    await waitFor('reload is back', () => h.shell.locator(RELOAD).count(), (n) => n === 1);
    expect(await busy(h, PAGE)).toBe(false);
  });

  it('R4 Esc stops it too', async () => {
    await openSlow();
    await pressInPage(h, 'Escape', [], PAGE);
    await waitFor('left out', () => stateOf(h, PAGE, 'never.gltf'), (s) => s === 'left-out', 2000);
    expect((await leftOut(h, PAGE))[0]!.why).toMatch(/stopped/);
  });

  it('R6 focus holds on its object when another goes, and moves on when its own goes', async () => {
    await openSlow();
    const outline = await holo<string[]>(h, 'window.__holoml.outline()', PAGE);
    // A label is named by its text, as a screen reader would read it.
    expect(outline).toEqual(['button:Label: First', 'button:Model: slow', 'button:Model: small', 'button:Label: After']);
    for (let i = 0; i < 4; i++) await pressInPage(h, 'Tab', [], PAGE);
    await waitFor('"After" in focus', () => focused(h, PAGE), (t) => t === 'Label: After');
    await pressInPage(h, 'Escape', [], PAGE);
    await waitFor('left out', () => stateOf(h, PAGE, 'never.gltf'), (s) => s === 'left-out');
    expect(await focused(h, PAGE)).toBe('Label: After');
    expect(await holo<string[]>(h, 'window.__holoml.outline()', PAGE)).toEqual(['button:Label: First', 'button:Model: small', 'button:Label: After']);

    await openSlow();
    await pressInPage(h, 'Tab', [], PAGE);
    await pressInPage(h, 'Tab', [], PAGE);
    await waitFor('"slow" in focus', () => focused(h, PAGE), (t) => t === 'Model: slow');
    await pressInPage(h, 'Escape', [], PAGE);
    await waitFor('focus moved to the next', () => focused(h, PAGE), (t) => t === 'Model: small');
  });

  it('R4 a model that never finishes is given up after 30 seconds', async () => {
    const started = await openSlow();
    await waitFor('given up', () => stateOf(h, PAGE, 'never.gltf'), (s) => s === 'left-out', 45_000);
    const took = Date.now() - started;
    expect(took).toBeGreaterThanOrEqual(29_000);
    expect(took).toBeLessThan(40_000);
    expect((await leftOut(h, PAGE))[0]!.why).toBe('still loading after 30 s');
    expect(await noticeText(h, PAGE)).toContain('still loading after 30 s');
  }, 60_000);
});

describe('R5: repeated visits', () => {
  let h: Harness;
  beforeAll(async () => {
    h = await launch(server.url('link-a.html'));
  });
  afterAll(async () => h?.close());

  /** The page process's memory after a full garbage collection, in MB. */
  async function pageMemoryMB(page: string): Promise<number> {
    await inDebugger(h, page, 'HeapProfiler.collectGarbage');
    await detachDebugger(h, page);
    await sleep(500);
    return h.app.evaluate(({ app, webContents }, page) => {
      const guest = webContents.getAllWebContents().filter((w) => w.getType() === 'webview' && w.getURL().includes(page)).pop()!;
      const pid = guest.getOSProcessId();
      const m = app.getAppMetrics().find((p) => p.pid === pid)!.memory;
      return (m.privateBytes ?? m.workingSetSize) / 1024;
    }, page);
  }

  async function visit(which: 'a' | 'b'): Promise<void> {
    const page = `heavy-${which}.holoml`;
    await open(h, server.url(`holoml/${page}`), page);
    await waitFor(`${page}'s models`, async () => (await models(h, page)).map((m) => m.state), (s) => s.length === 3 && s.every((x) => x === 'loaded'), 30_000);
  }

  it('R5 ten visits back and forth leave the page process where it was after the first', async () => {
    await visit('a');
    const first = await pageMemoryMB('heavy-a.holoml');
    for (let i = 0; i < 10; i++) await visit(i % 2 === 0 ? 'b' : 'a');
    const last = await pageMemoryMB('heavy-a.holoml');
    console.log(`[R5] page process: ${first.toFixed(0)} MB after the first visit, ${last.toFixed(0)} MB after ten more`);
    // One page's models hold about 60 MB: a page kept after it goes would show.
    expect(last).toBeLessThan(first + 40);
  }, 240_000);
});

describe('R6, R7, R8: keyboard, screen readers, and motion', () => {
  let h: Harness;
  const PAGE = 'still.holoml';
  beforeAll(async () => {
    h = await launch(server.url('holoml/still.holoml'));
    await waitForPage(h, PAGE);
    await sceneReady(h, PAGE);
  });
  afterAll(async () => h?.close());

  const OUTLINE = [
    'button:Model: car',
    'button:Group: stand',
    'button:Model: placeholder-car.gltf',
    `a:Link to ${'SECOND'}`,
    'a:More cars',
    'button:Label: The red car',
    'button:Model: far',
  ];
  const expected = () => OUTLINE.map((s) => s.replace('SECOND', server.url('holoml/second.holoml')));

  it('R6 Tab reaches every link and named thing in page order, each outlined in the scene; Enter follows a link', async () => {
    await clickAt(h, await project(h, 20, 20)); // into the page, on empty space
    expect(await holo<string[]>(h, 'window.__holoml.outline()', PAGE)).toEqual(expected());
    for (const [i, item] of expected().entries()) {
      await pressInPage(h, 'Tab', [], PAGE);
      const text = item.slice(item.indexOf(':') + 1);
      await waitFor(`item ${i} in focus`, () => focused(h, PAGE), (t) => t === text);
      const box = await holo<{ visible: boolean; min: Vec; max: Vec }>(h, 'window.__holoml.highlight()', PAGE);
      // The far model was refused (another site): it is marked, and the mark is outlined.
      expect(box.visible, `outline for ${item}`).toBe(true);
    }
    await pressInPage(h, 'Tab', ['shift'], PAGE);
    await pressInPage(h, 'Tab', ['shift'], PAGE);
    await waitFor('the label link in focus', () => focused(h, PAGE), (t) => t === 'More cars');
    await pressInPage(h, 'Enter', [], PAGE);
    await waitFor('followed', async () => (await focusedTab(h)).url, (u) => u === server.url('holoml/second.holoml#top'));
    await pressInShell(h, 'Left', ['alt']);
    await waitFor('back', async () => (await focusedTab(h)).url, (u) => u === server.url('holoml/still.holoml'));
    await sceneReady(h, PAGE);
  });

  it('R7 the accessibility tree has the title, each named thing, and each link with its address', async () => {
    const tree = await inDebugger<{ nodes: { role?: { value: string }; name?: { value: string }; ignored: boolean; properties?: { name: string; value: { value: unknown } }[] }[] }>(
      h,
      PAGE,
      'Accessibility.getFullAXTree',
    );
    await detachDebugger(h, PAGE);
    const shown = tree.nodes.filter((n) => !n.ignored).map((n) => ({ role: n.role?.value ?? '', name: n.name?.value ?? '', props: n.properties ?? [] }));
    expect(shown.some((n) => n.role === 'heading' && n.name === 'HoloML still scene')).toBe(true);
    expect(shown.some((n) => n.role === 'navigation' && n.name === 'Scene outline')).toBe(true);
    for (const name of ['Model: car', 'Group: stand', 'Label: The red car', 'Model: far']) {
      expect(shown.some((n) => n.role === 'button' && n.name === name), name).toBe(true);
    }
    const links = shown.filter((n) => n.role === 'link');
    expect(links.map((l) => l.name)).toEqual([`Link to ${server.url('holoml/second.holoml')}`, 'More cars']);
    const hrefs = await inPage<string[]>(h, '[...document.querySelectorAll("#holoml-outline a")].map((a) => a.href)', PAGE);
    expect(hrefs).toEqual([server.url('holoml/second.holoml'), server.url('holoml/second.holoml#top')]);
  });

  it('R8 the text view shows the same names and links as a plain page, from the button and from Ctrl+Shift+V', async () => {
    const outlineText = expected().map((s) => s.slice(s.indexOf(':') + 1));
    await h.shell.click('hs-toolbar [data-testid="text-view"]');
    await waitFor('the text view', () => holo<boolean>(h, 'window.__holoml.textView', PAGE), (v) => v === true);
    await waitFor('the button pressed', () => h.shell.locator('hs-toolbar [data-testid="text-view"]').getAttribute('aria-pressed'), (v) => v === 'true');
    const page = await inPage<{ canvas: boolean; text: string[]; title: string }>(
      h,
      `({ canvas: getComputedStyle(document.getElementById('holoml-root')).display !== 'none',
          text: [...document.querySelectorAll('#holoml-outline li')].filter((li) => li.getBoundingClientRect().height > 0).map((li) => li.textContent),
          title: document.querySelector('#holoml-outline-nav h1').textContent })`,
      PAGE,
    );
    expect(page.canvas).toBe(false);
    expect(page.title).toBe('HoloML still scene');
    expect(page.text).toEqual(outlineText);
    // Ctrl+Shift+V in the page, then in the shell, switches it back and forth.
    await pressInPage(h, 'V', ['control', 'shift'], PAGE);
    await waitFor('3D again', () => holo<boolean>(h, 'window.__holoml.textView', PAGE), (v) => v === false);
    // The shell has heard: the button shows the 3D view again.
    await waitFor('the button released', () => h.shell.locator('hs-toolbar [data-testid="text-view"]').getAttribute('aria-pressed'), (v) => v === 'false');
    await h.shell.locator('hs-toolbar [data-testid="text-view"]').focus();
    await h.shell.keyboard.press('Control+Shift+V');
    await waitFor('text again, from the shell', () => holo<boolean>(h, 'window.__holoml.textView', PAGE), (v) => v === true);
    await h.shell.click('hs-toolbar [data-testid="text-view"]');
    await waitFor('3D again', () => holo<boolean>(h, 'window.__holoml.textView', PAGE), (v) => v === false);
  });

  it('R8 with reduced motion, animations show their end at once', async () => {
    const ANIM = 'animated.holoml';
    await open(h, server.url(`holoml/${ANIM}`), ANIM);
    // The setting stays with the tab: the next visit starts with reduced motion on.
    await inDebugger(h, ANIM, 'Emulation.setEmulatedMedia', { features: [{ name: 'prefers-reduced-motion', value: 'reduce' }] });
    try {
      await open(h, server.url(`holoml/${ANIM}?still`), `${ANIM}?still`);
      expect(await inPage<boolean>(h, 'matchMedia("(prefers-reduced-motion: reduce)").matches', ANIM)).toBe(true);
      // The label's rise is at its end without waiting its 400 ms; the turntable stands still.
      await waitFor('models', async () => (await models(h, ANIM)).map((m) => m.state), (s) => s.every((x) => x === 'loaded'));
      expect((await holo<{ position: Vec }>(h, 'window.__holoml.object("sign")', ANIM))!.position[1]).toBe(3);
      const r1 = (await holo<{ rotation: Vec }>(h, 'window.__holoml.object("turntable")', ANIM))!.rotation[1];
      const spin1 = (await models(h, ANIM)).find((m) => m.animation?.name === 'Spin' && m.src.includes('spinner'))!;
      await sleep(600);
      const r2 = (await holo<{ rotation: Vec }>(h, 'window.__holoml.object("turntable")', ANIM))!.rotation[1];
      const spin2 = (await models(h, ANIM)).find((m) => m.animation?.name === 'Spin' && m.src.includes('spinner'))!;
      expect(r2).toBe(r1);
      expect(spin2.animation!.time).toBe(spin1.animation!.time);
    } finally {
      await detachDebugger(h, ANIM);
    }
  });
});

describe('R9: the inspector', () => {
  let h: Harness;
  const PAGE = 'still.holoml';
  const INST = (id: string) => `hs-instruments [data-testid="${id}"]`;
  beforeAll(async () => {
    h = await launch(server.url('holoml/still.holoml'), { userDataDir: newProfile({ layersOnOpen: false, instruments: true }) });
    await waitForPage(h, PAGE);
    await sceneReady(h, PAGE);
  });
  afterAll(async () => h?.close());

  const detail = () => h.shell.locator(INST('inst-scene-detail')).innerText();

  it('R9 picking an object shows its source line, bounds, transforms, and costs', async () => {
    await waitFor('the Scene part', () => h.shell.locator(INST('inst-scene')).count(), (n) => n === 1);
    await waitFor('the tree', () => h.shell.locator(`${INST('inst-scene-tree')} button`).count(), (n) => n > 5);
    await h.shell.click(INST('inst-scene-pick'));
    await waitFor('pick on', () => h.shell.locator(INST('inst-scene-pick')).getAttribute('aria-pressed'), (v) => v === 'true');
    const car = await holo<Point | null>(h, 'window.__holoml.point("car")', PAGE);
    const at = await project(h, car!.x, car!.y);
    await clickUntil(h, at, 'the car picked', async () => (await h.shell.locator(INST('inst-scene-source')).count()) === 1 && (await detail()).includes('id="car"'));
    const text = await detail();
    expect(text).toContain('Line 11, column 5');
    expect(await h.shell.locator(INST('inst-scene-source')).innerText()).toContain('<model id="car" src="models/placeholder-car.gltf" rotation="0 30 0">');
    expect(await h.shell.locator(INST('inst-scene-bounds')).innerText()).toMatch(/^-?[\d.]+, -?[\d.]+, -?[\d.]+ to -?[\d.]+, -?[\d.]+, -?[\d.]+$/);
    expect(await h.shell.locator(INST('inst-scene-position')).innerText()).toBe('0.00, 0.00, 0.00');
    expect(text).toMatch(/Rotation\s+0°, 30°, 0°/);
    expect(text).toMatch(/Scale\s+1.00, 1.00, 1.00/);
    expect(Number((await h.shell.locator(INST('inst-scene-triangles')).innerText()).replace(/,/g, ''))).toBeGreaterThan(0);
    // Picking does not follow links.
    const linked = await holo<Point | null>(h, 'window.__holoml.point(0)', PAGE);
    await clickUntil(h, await project(h, linked!.x, linked!.y), 'the linked model picked', async () => (await detail()).includes('id="linked"'));
    expect((await focusedTab(h)).url).toBe(server.url('holoml/still.holoml'));
    await h.shell.click(INST('inst-scene-pick'));
    await waitFor('pick off', () => h.shell.locator(INST('inst-scene-pick')).getAttribute('aria-pressed'), (v) => v === 'false');
  });

  it('R9 problems and models that failed are listed with line and column', async () => {
    const problems = await h.shell.locator(INST('inst-scene-problems')).innerText();
    // The far model names another site (line 25): refused.
    expect(problems).toMatch(/25:5 model far refused/);
  });

  it('R9 it all works from the keyboard', async () => {
    const first = h.shell.locator(`${INST('inst-scene-tree')} button`).first();
    await first.focus();
    await h.shell.keyboard.press('Enter');
    await waitFor('the first selected', () => detail(), (t) => /Line \d+, column \d+/.test(t));
    const before = await detail();
    await h.shell.keyboard.press('ArrowDown');
    await waitFor('the next selected', () => detail(), (t) => t !== before);
    const current = await h.shell.locator(`${INST('inst-scene-tree')} button[aria-current="true"]`).count();
    expect(current).toBe(1);
    expect(await h.shell.evaluate(() => (document.querySelector('hs-instruments')!.shadowRoot!.activeElement as HTMLElement | null)?.dataset['index'])).toBe('1');
    await h.shell.keyboard.press('End');
    await waitFor('the last selected', () => h.shell.evaluate(() => (document.querySelector('hs-instruments')!.shadowRoot!.activeElement as HTMLElement | null)?.dataset['index']), (i) => Number(i) > 5);
    // The pick button is reached and pressed from the keyboard too.
    await h.shell.locator(INST('inst-scene-pick')).focus();
    await h.shell.keyboard.press('Space');
    await waitFor('pick on', () => h.shell.locator(INST('inst-scene-pick')).getAttribute('aria-pressed'), (v) => v === 'true');
    await h.shell.keyboard.press('Space');
    await waitFor('pick off', () => h.shell.locator(INST('inst-scene-pick')).getAttribute('aria-pressed'), (v) => v === 'false');
  });

  it('R9 the Scene part is only there for HoloML pages', async () => {
    await shellCall(h, 'showUrl', server.url('link-a.html'));
    await waitForPage(h, 'link-a.html');
    await waitFor('the Scene part gone', () => h.shell.locator(INST('inst-scene')).count(), (n) => n === 0);
  });
});
